swagger: '2.0'
info:
  description: 'This API allows you to calculate the value of your settlement using the insured''s data.'
  version: '1.0'
  title: Insured API
host: localhost:8080
basePath: /api/v1/secured
tags:
  - name: insured-controller
    description: Insured Controller
paths:
  /calculateLiquidation:
    post:
      tags:
        - insured-controller
      summary: Calculate Liquidation
      operationId: calculateLiquidation
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: insuredRequestDto
          description: Insured data
          required: true
          schema:
            $ref: '#/definitions/InsuredRequestDto'
          examples:
            $ref: '#/examples/InsuredRequestDtoExample'

      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/LiquidationResponseDto'
          examples:
            $ref: '#/examples/LiquidationResponseDtoExample'
        '500':
          description: Internal Server Error
          schema:
            type: string
definitions:
  InsuredRequestDto:
    type: object
    properties:
      identificationType:
        type: integer
        format: int64
      identificationNumber:
        type: string
      insuredAmount:
        type: number
      dateOfBirth:
        type: string
        format: date
    required:
      - identificationType
      - identificationNumber
      - insuredAmount
      - dateOfBirth

  LiquidationResponseDto:
    type: object
    properties:
      identificationType:
        type: integer
        format: int64
      identificationNumber:
        type: string
      insuredValue:
        type: number
      liquidation:
        type: array
        items:
          $ref: '#/definitions/ProtectionResponseDto'
      totalValue:
        type: number

  ProtectionResponseDto:
    type: object
    properties:
      protectionCode:
        type: integer
        format: int64
      protectionName:
        type: string
      premiumValue:
        type: number

examples:
  InsuredRequestDtoExample:
    value:
      identificationType: 1
      identificationNumber: "51000002"
      insuredAmount: 100000
      dateOfBirth: "2003-03-22"
  LiquidationResponseDtoExample:
    value:
      identificationType: 1
      identificationNumber: "51000002"
      insuredValue: 100000
      liquidation:
        - protectionCode: 1
          protectionName: "Muerte accidental"
          premiumValue: 2000.00
        - protectionCode: 2
          protectionName: "Desmembración"
          premiumValue: 18000.00
        - protectionCode: 3
          protectionName: "Auxilio funerario"
          premiumValue: 14000.00
        - protectionCode: 4
          protectionName: "Renta vitalicia"
          premiumValue: 12000.00
      totalValue: 46000.00
